### ISSUE TITLE
Pimple is a requirement. Why?

### ISSUE THREAD

**Issue by adammbalogh** [dflydev/dflydev-stack-basic-authentication#2]
It should not depend on Pimple.

(or you should add the requirement to the composer.json at least)

**Comment by simensen** [comment]
I missed this because I require-dev Silex which gets Pimple. The fact that I didn't require Pimple but it works for me and for testing was just a sad coincidence. :(

If you want to add it as a dependency to composer.json I'll merge it. Otherwise, I'll keep this open to try and remember to do it myself later.

Long-term goal would be to eventually replace Pimple w/ some of these as we _are_ using it, but requiring all of Pimple itself for what we are using it for is probably overkill.

**Comment by adammbalogh** [comment]
Yeah you're right. Anyway pimple is so small, it does not hurt anyone.

**Comment by andig** [comment]
> It should not depend on Pimple.

+1 for not requiring pimple
